In [27]:
import pandas as pd
import numpy as np

In [28]:
data=pd.read_csv(r"C:\Users\ASUS\Downloads\archive (11)\Churn_Modelling.csv")

In [29]:
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [30]:
!pip install ipykernel

Requirement already satisfied: ipykernel in c:\users\asus\anaconda3\lib\site-packages (6.31.0)
Requirement already satisfied: comm>=0.1.1 in c:\users\asus\anaconda3\lib\site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\asus\anaconda3\lib\site-packages (from ipykernel) (1.8.16)
Requirement already satisfied: ipython>=7.23.1 in c:\users\asus\anaconda3\lib\site-packages (from ipykernel) (9.7.0)
Requirement already satisfied: jupyter-client>=8.0.0 in c:\users\asus\anaconda3\lib\site-packages (from ipykernel) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\asus\anaconda3\lib\site-packages (from ipykernel) (5.8.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\asus\anaconda3\lib\site-packages (from ipykernel) (0.2.1)
Requirement already satisfied: nest-asyncio>=1.4 in c:\users\asus\anaconda3\lib\site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: packaging>=22 in c:\users\asus\anaconda3\lib\site-packages (from ipykernel) (25.0)
Requirement already satisfied: psutil>=5.7 in c:\users\asus\anaconda3\lib\site-packages (from ipykernel) (7.0.0)
Requirement already satisfied: pyzmq>=25 in c:\users\asus\anaconda3\lib\site-packages (from ipykernel) (27.1.0)
Requirement already satisfied: tornado>=6.2 in c:\users\asus\anaconda3\lib\site-packages (from ipykernel) (6.5.1)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\asus\anaconda3\lib\site-packages (from ipykernel) (5.14.3)
Requirement already satisfied: colorama>=0.4.4 in c:\users\asus\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in c:\users\asus\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\asus\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in c:\users\asus\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\asus\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in c:\users\asus\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\asus\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: wcwidth in c:\users\asus\anaconda3\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\asus\anaconda3\lib\site-packages (from jedi>=0.18.1->ipython>=7.23.1->ipykernel) (0.8.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\anaconda3\lib\site-packages (from jupyter-client>=8.0.0->ipykernel) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\asus\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel) (4.5.0)
Requirement already satisfied: pywin32>=300 in c:\users\asus\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel) (311)
Requirement already satisfied: six>=1.5 in c:\users\asus\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=8.0.0->ipykernel) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\asus\anaconda3\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\asus\anaconda3\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (3.0.0)
Requirement already satisfied: pure_eval in c:\users\asus\anaconda3\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (0.2.3)

In [31]:
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
import pickle

In [32]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [33]:
#Droping the irrelevant  columns
data=data.drop(columns=['RowNumber','CustomerId','Surname'],axis=1)

In [34]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [35]:
#Checking is there any null values are there are not
data.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [36]:
data.describe()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [37]:
data.shape

(10000, 11)

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  object
 2   Gender           10000 non-null  object
 3   Age              10000 non-null  int64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB

In [39]:
data.tail()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [40]:
#Encoding the categorical values
label=LabelEncoder()
data['Gender']=label.fit_transform(data['Gender'])

In [41]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  object
 2   Gender           10000 non-null  int64
 3   Age              10000 non-null  int64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(2), int64(8), object(1)
memory usage: 859.5+ KB

In [50]:
#I need to convert geography using one hot encoding
from sklearn.preprocessing import OneHotEncoder
one_label=OneHotEncoder()
one_encoded=one_label.fit_transform(data[['Geography']])

In [55]:
one_encoded.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [56]:
columns = one_label.get_feature_names_out(['Geography'])
columns

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [58]:
geo_encoded=pd.DataFrame(one_encoded.toarray(),columns = one_label.get_feature_names_out(['Geography'])
)

In [59]:
geo_encoded

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [63]:
#Combine all the one hot encoded columns
data=pd.concat([data.drop('Geography',axis=1),geo_encoded],axis=1)

In [64]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [65]:
#Divide the data set into dependent and independent
x=data.drop('Exited',axis=1)
y=data["Exited"]

In [66]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [67]:
x

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,1.0,0.0,0.0

In [69]:
# i want to split my data into train and test
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [71]:
# Scaling the features
salar=StandardScaler()
x_test=salar.fit_transform(x_test)
x_train=salar.transform(x_train)

APPLYING ANN IMPLEMENTATION

In [72]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping
import datetime

In [82]:
!pip install tensorboard

Collecting tensorboard
  Downloading tensorboard-2.21.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: absl-py>=0.4 in c:\users\asus\anaconda3\lib\site-packages (from tensorboard) (2.5.0)
Requirement already satisfied: grpcio<2.0,>=1.74.0 in c:\users\asus\anaconda3\lib\site-packages (from tensorboard) (1.82.1)
Requirement already satisfied: markdown>=2.6.8 in c:\users\asus\anaconda3\lib\site-packages (from tensorboard) (3.8)
Requirement already satisfied: numpy>=1.12.0 in c:\users\asus\anaconda3\lib\site-packages (from tensorboard) (2.3.5)
Requirement already satisfied: packaging in c:\users\asus\anaconda3\lib\site-packages (from tensorboard) (25.0)
Requirement already satisfied: pillow in c:\users\asus\anaconda3\lib\site-packages (from tensorboard) (12.0.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\asus\anaconda3\lib\site-packages (from tensorboard) (7.35.1)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\asus\anaconda3\lib\site-packages (from tensorboard) (80.9.0)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard)
  Downloading tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\asus\anaconda3\lib\site-packages (from tensorboard) (3.1.3)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\asus\anaconda3\lib\site-packages (from grpcio<2.0,>=1.74.0->tensorboard) (4.15.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\asus\anaconda3\lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.2)
Downloading tensorboard-2.21.0-py3-none-any.whl (5.5 MB)
   ---------------------------------------- 0.0/5.5 MB ? eta -:--:--
   ------------- -------------------------- 1.8/5.5 MB 12.6 MB/s eta 0:00:01
   ---------------------------------------  5.5/5.5 MB 15.1 MB/s eta 0:00:01
   ---------------------------------------- 5.5/5.5 MB 14.3 MB/s  0:00:00
Downloading tensorboard_data_server-0.7.2-py3-none-any.whl (2.4 kB)
Installing collected packages: tensorboard-data-server, tensorboard

   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   ---------------------------------------- 2/2 [tensorboard]

Successfully installed tensorboard-2.21.0 tensorboard-data-server-0.7.2

In [73]:
#Building an ANN Model
model=Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid')
])

c:\Users\ASUS\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [76]:
#compile the model
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [79]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
log_dir='logs/fit'+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [84]:
#Set up early Stopping
early_stopping_callback=EarlyStopping(monitor="val_loss",patience=10,restore_best_weights=True)

In [85]:
#training the neural network model
history=model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=100,
                  callbacks=[tensorflow_callback,early_stopping_callback])

Epoch 1/100

250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8665 - loss: 0.3198 - val_accuracy: 0.8640 - val_loss: 0.3419
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8676 - loss: 0.3177 - val_accuracy: 0.8575 - val_loss: 0.3427
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8668 - loss: 0.3166 - val_accuracy: 0.8570 - val_loss: 0.3471
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8709 - loss: 0.3140 - val_accuracy: 0.8610 - val_loss: 0.3429
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8689 - loss: 0.3128 - val_accuracy: 0.8570 - val_loss: 0.3472
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8714 - loss: 0.3119 - val_accuracy: 0.8600 - val_loss: 0.3458
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8699 - loss: 0.3110 - val_accuracy: 0.8545 - val_loss: 0.3476
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8694 - loss: 0.3095 - val_accuracy: 0.8605 - val_loss: 0.3464
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8736 - loss: 0.3075 - val_accuracy: 0.8600 - val_loss: 0.3481
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8710 - loss: 0.3073 - val_accuracy: 0.8605 - val_loss: 0.3487
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8700 - loss: 0.3054 - val_accuracy: 0.8600 - val_loss: 0.3461

In [86]:
model.save("model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [91]:
#Load Tensor Board Extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [ ]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 22600), started 0:04:20 ago. (Use '!kill 22600' to kill it.)